### ISSUE TITLE
Investigate offline mutation store

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix-android#10]
First investigation for #5
## Idea

Investigate how offline mutations can be stored inside the Android library. 
Offline changes need to be persisted just in case the application will be restarted. Applications can be offline for a long time so we might need to have separate stores for offline data.

## Proposal

Store mutations in SQL database - sql lite
Store mutations only when offline (based on the offline state provided by broadcast)
Remove mutations from the store once they are processed by the server.

## How this may be done

We could hook into Apollo Client and log to console (logcat) all mutation operations that are happening. This will help us to understand how graphql operations work and how they look like and how we can hook into request chain for Apollo Android.

Once we will be able to read all incoming mutations we can investigate the preferred way to store them inside some local database. We can use existing SQLite database capabilities available on Android. 

Once we have all mutations stored we can visualize them as separate view in the example app. 

The next step may be to store mutations only when the device is offline by registering a specific broadcast inside the application.

**Comment by wtrocki** [comment]
@harshithdwivedi WDYT about this? Do you think it is useful to do it over the next week? Feel free to propose alternative flow.

**Comment by wtrocki** [comment]
ping @Lavanyagaur22

**Comment by harshithdwivedi** [comment]
@wtrocki Perfect, looks good to me :+1:
I believe that researching this can be a worthwhile investment.

**Comment by Lavanyagaur22** [comment]
* What went wrong:
Some problems were found with the configuration of task ':sample:generateDebugApolloIR'.
> Value 'main GraphQL source' specified for property '$1' cannot be converted to a file.
> Value 'debug GraphQL source' specified for property '$2' cannot be converted to a file.

execution failed for configuration of task ':sample:generateDebugApolloIR'

When building the project I am facing this error, I tried to fix it out by changing the gradle version and adding "ext.apolloGraphQL_version = '0.4.3' " , ( https://github.com/apollographql/apollo-android/issues/601 )but no success. @harshithdwivedi @wtrocki @danielpassos Can you please help me out.

**Comment by harshithdwivedi** [comment]
@Lavanyagaur22 can you push your changes onto a branch?
I'll look into it

**Comment by wtrocki** [comment]
Looks like typical problem with missconfigured code generator. Where did we put the app schema? Are we using showcase schema or somthing else?

**Comment by Lavanyagaur22** [comment]
@wtrocki We are using the showcase schema right? Schema is put under "sample/src/main/graphql/org/aerogear/graphqlandroid/schema.json"

Also studio showing this:

<img width="1410" alt="Screenshot 2019-06-04 at 9 11 07 AM" src="https://user-images.githubusercontent.com/33238323/58849638-b7ee8280-86a8-11e9-96ff-74bbda7d05fe.png">

**Comment by Lavanyagaur22** [comment]
> @Lavanyagaur22 can you push your changes onto a branch?
> I'll look into it

#18  @harshithdwivedi pushed the code

**Comment by Lavanyagaur22** [comment]
> Applications can be offline for a long time so we might need to have separate stores for offline data.

@wtrocki What exactly do you mean by having separate stores?

**Comment by Lavanyagaur22** [comment]
@wtrocki @harshithdwivedi It's working with the previous version of gradle ( that is Apollo generated code and stuff ) but not with the latest one

**Comment by harshithdwivedi** [comment]
Hm, maybe it's worthwhile to check the apollo-graphql repo's issues to see
if their users are facing the same issue.
If not then I'd recommend that you go ahead and open an issue for this.

For now, we can go ahead with the version of gradle with which the app
works; what's that version Btw?

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi gradle 4.6

**Comment by harshithdwivedi** [comment]
Cool, go ahead with it.

**Comment by wtrocki** [comment]
> @wtrocki What exactly do you mean by having separate stores?

Cache represent server side data that user fetched. 
If we start adding things to cache that actually do not represent the state of the server it will mean that:

- cache is no longer actual cache but the actually client-side store
- we need to build another layer on top of the current cache that will represent this offline changes
- we will need to deal with complex cache invalidation and listeners that also should be reattached once the application is restarted.
- Requires reimplementing currrenty functional cache mechanism

I really support you guys with any technical decision that we make here.
What I have suggested is just simple and independent mechanism that we can implement without writing phd thesis on data replication mechanism. 

Separate store simplifies that as it will mean that we do not need to write custom cache. It is a great way to start without exploring and hitting so many problems with cache mechanisms.

We really do not want to deal with caching. Why.. Going to use this tweet as answer :P

https://twitter.com/codinghorror/status/506010907021828096?lang=en

**Comment by Lavanyagaur22** [comment]
@wtrocki When mutation results are successfully stored in the server(when online), does the server returns any kind of success (like any kinda callback on successful operation)?

**Comment by wtrocki** [comment]
Yes.. Mutate method should return rxobservable. - depending what wrapper we use

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi @wtrocki Can you have a look at this 

https://drive.google.com/file/d/1sj_IMfPGYvma51VWV6K6fbbtOxpy5zfE/view?usp=sharing

More modifications to be done :p

**Comment by Lavanyagaur22** [comment]
What is the advantage  of having "status" field in the schema?

**Comment by Lavanyagaur22** [comment]
Create { title: 'Task6', description: 'This is task6', status: 'OPEN' }

{"level":30,"time":1559743931609,"pid":6674,"hostname":"lavanyas-MacBook-Pro.local","tag":"AUDIT","audit":{"logType":"RESOLVER_COMPLETION",**"msg":"insert into \"tasks\" (\"description\", \"status\", \"title\", \"version\") values ($1, $2, $3, $4) returning * - column \"status\" of relation \"tasks\" does not exist"**,"operationType":"mutation","fieldName":"createTask","parentTypeName":"Mutation","path":"createTask","success":false,"arguments":{"title":"Task6","description":"This is task6”,"status":"OPEN"},"authenticated":false},"v":1}

@wtrocki Why is this error coming when creating a new one?

**Comment by wtrocki** [comment]
Sounds like backend problem `column "status" of relation "tasks" does not exist`.
Loooks like db container needs to be killed and recreated

To fix it:
```
docker ps
docker kill containerid
```

or 
``` 
docker-compose down
docker-compose kill 
docker-compose up
```

**Comment by wtrocki** [comment]
Btw. Lets include link to server project in Readme so it will be clear where it comes from.

**Comment by Lavanyagaur22** [comment]
https://github.com/apollographql/apollo-android/tree/master/apollo-kotlin-sample 
This is also very nice to understand how different things in apollo android works :) . This is a new one added there :p

**Comment by wtrocki** [comment]
@Lavanyagaur22 Kudos for finding this example and playing with it. 
You do not need mentors :) mentors need you :D
