### ISSUE TITLE
Discussion: Finding base from cache (Apollo Normalised Cache)

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/offix-android#102]
In this issue, we can discuss approaches to read the apollo cache and find the base from the cache.

**Comment by wtrocki** [comment]
Any update on this field?

**Comment by Lavanyagaur22** [comment]
> Any update on this field?

No, not till now. Was working on sample app and subscriptions. This is the next issue to work upon.

**Comment by wtrocki** [comment]
No worries. I was more curious than asking

**Comment by wtrocki** [comment]
Let's settle with simple approach for the moment
