### ISSUE TITLE
Simplify the sample app

### ISSUE THREAD

**Issue by harshithdwivedi** [aerogear/offix-android#106]
Let's keep the sample app as simple as possible.
Currently, it's overloaded with things that the developer doesn't need to know; for example, MVVM Architecture, ViewModels, etc.

Let's get rid of them and have a basic android app with as few java/kotlin files as possible.

**Comment by Lavanyagaur22** [comment]
Yeah, the users would get a better understanding of the library then.

**Comment by wtrocki** [comment]
Agreed. We landed server so we might also integrate with new server side and give developers nice end to end example

**Comment by harshithdwivedi** [comment]
Created #107

**Comment by wtrocki** [comment]
Love it! I actually went quickly into sample app and it is really huge in terms of code that is not offix related, so our initial proposal to use patterns for implementation do not work nicely. making it simple should not require a lots of work anyway and extended schema can give us much more freedom.

Ping me if you get any questions about server schema.

**Comment by harshithdwivedi** [comment]
This is completed
