### ISSUE TITLE
Make the library support the new server

### ISSUE THREAD

**Issue by harshithdwivedi** [aerogear/offix-android#107]
We need to test the library on the new server with the updated schema.
It would be good to see what roadblocks we hit and how to remove them.

The biggest challenge I see is handling offline mutations; @Lavanyagaur22 maybe we can get rid of the current implementation and see if there's a way for us to catch the outbound requests inside the interceptor itself.

We can have a second interceptor called OfflineInterceptor that processes the requests (instead of responses) and stores them into an ArrayList for future use.

P.S. Let's start with support for the offline case where the app is in foreground.

@wtrocki @Lavanyagaur22 Appreciate your thoughts on this.

**Comment by wtrocki** [comment]
@harshithdwivedi Love it!

> P.S. Let's start with support for the offline case where the app is in foreground.

Yes!

**Comment by harshithdwivedi** [comment]
Closing this
