### ISSUE TITLE
Query regarding generating schema file in sample app using server.

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/offix-android#109]
@wtrocki Graphback generates the schema file in .ts format. How can we get it in json format?

**Comment by Lavanyagaur22** [comment]
Also @wtrocki @harshithdwivedi I am facing some problems while generating query and mutation files with relationships. Can you please help me out regarding that?

**Comment by harshithdwivedi** [comment]
Hm, i tried running graphback generate but it only generated the .ts files and not json
Maybe @wtrocki has some idea?

**Comment by Lavanyagaur22** [comment]
Also, this is the mutation file I have created based on the schema in the server.

```graphql
mutation checkAndUpdateTask($id: ID!, $title: String, $description: String, $version: Int!, $status: String!){
    checkAndUpdateTask(id: $id, title: $title, description: $description, version: $version, status: $status){
        id
        version
        title
        description
        status
        creationMetadata{
            createdDate
            createdBy{
                id
                firstName
                lastName
                title
                email
            }
        }
        assignedTo{
            id
            firstName
            lastName
            title
            email
        }
    }
}
```

**Comment by Lavanyagaur22** [comment]
@wtrocki Can we add `type query` in the schema too? This would help us in querying and getting lists of tasks which will help us in UI bindings in the sample.

**Comment by Lavanyagaur22** [comment]
@wtrocki @harshithdwivedi Can you please add type query in the schema too? This would help us in querying and getting lists of tasks which will help us in UI bindings in the sample.

**Comment by wtrocki** [comment]
@Lavanyagaur22 Server is now part of the offix-android so please add anything to the schema that you will require. 

Apollo provides CLI for generating JSON file. Servers will never expose any json file, but if you think that is required let me know.  https://github.com/apollographql/apollo-tooling#apollo-clientdownload-schema-output

**Comment by wtrocki** [comment]
Btw.. This server is simply now Apollo GraphQL server - we do not need to use Graphback anymore - it just gave us implementation we required.

**Comment by wtrocki** [comment]
> I am facing some problems 

Can we be more specific?
If there is issue with generated code let me know. We can create issue in graphback and fix it. For custom code fee free to change stuff etc.

**Comment by wtrocki** [comment]
>  Can you please add type query in the schema too

Not sure what you mean by type Query. Check playground there are queries there.
