### ISSUE TITLE
Getting error while running server.

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/offix-android#110]
While starting the server and running `graphback db` command I am getting this error: `password authentication failed for user "lavanya"` .
@wtrocki Can you please help me out in this?

**Comment by Lavanyagaur22** [comment]
For generating a schema from apollo CLI command, we need the endpoint URL of the server and I am getting the above error in an attempt to run the server. Help required :)

**Comment by harshithdwivedi** [comment]
Looks like a postgres error, but we shouldn't be getting it since we are using sqlite.

**Comment by Lavanyagaur22** [comment]
> Looks like a postgres error, but we shouldn't be getting it since we are using sqlite.

Yep, when I searched the error, it was related to postgres. So not sure why the error came.
