### ISSUE TITLE
Maintain a Queue of user provided callbacks

### ISSUE THREAD

**Issue by harshithdwivedi** [aerogear/offix-android#115]
WRT #114, let's keep a queue of the user-provided callbacks instead of a single callback variable.

**Comment by wtrocki** [comment]
@harshithdwivedi Really important. We can have multiple callbacks running at the same time so we will get some issues around that.

**Comment by wtrocki** [comment]
@harshithdwivedi Really important. We can have multiple callbacks running at the same time so we will get some issues around that.

**Comment by harshithdwivedi** [comment]
Fixed in #117
