### ISSUE TITLE
Adding subscriptions in sample.

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/offix-android#121]
Adding subscriptions in server schema of sample.

**Comment by Lavanyagaur22** [comment]
@wtrocki We need to add `type subscriptions` for update and create a mutation in server schema, right?

**Comment by wtrocki** [comment]
Actually this is because servers config.json has this disabled. To enable simply check what subscription types you want in app and execute `graphback generate` 

Remember to try subscription in playground first to get feeling how it works
