### ISSUE TITLE
Add subscriptions in sample.

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/offix-android#135]
This is the *error log* when I am trying to build generated files after adding  subscriptions file:

```

> Task :sample:generateDebugApolloIR FAILED
.../main/graphql/org.aerogear.graphqlandroid/subNewTask.graphql: Schema is not configured for subscriptions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sample:generateDebugApolloIR'.
> Process 'command '/Users/lavanya/GsocJboss'2019/voyager-android/sample/.gradle/nodejs/node-v6.7.0-darwin-x64/bin/node'' finished with non-zero exit value 1
```

But we have schema configured for subscriptions.

<img width="1440" alt="Screenshot 2019-08-20 at 9 48 20 PM" src="https://user-images.githubusercontent.com/33238323/63364983-4a432000-c394-11e9-915e-568ba2f693ae.png">

**Comment by Lavanyagaur22** [comment]
Subscriptions Files are in pr #136

**Comment by harshithdwivedi** [comment]
@Lavanyagaur22 can you try updating the Apollo client and the gradle version to see if that fixes the problem?

**Comment by Lavanyagaur22** [comment]
> @Lavanyagaur22 can you try updating the Apollo client and the gradle version to see if that fixes the problem?

Yeah trying same 👍

**Comment by Lavanyagaur22** [comment]
I tried (code pushed for updated dependency), still same error @harshithdwivedi

**Comment by Lavanyagaur22** [comment]
Resolved!
