### ISSUE TITLE
Update docs - Add sample demo in docs.

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/offix-android#160]
## Feature Request

Run the sample app. Try various features in it. Record a gif of it and upload it to `demo.md` file to update the docs.

**Comment by hussainashraf** [comment]
when  i try to run the sample app it throws me this error

Debugger attached.
Waiting for the debugger to disconnect...
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'c:\Users\hussain\Desktop\jboss\offix-android'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Process exited with code 1
Uncaught Error: Cannot find module 'c:\Users\hussain\Desktop\jboss\offix-android'

**Comment by FareesHussain** [comment]
@Lavanyagaur22 is this available to work.

I see the pr is created 2 year back on this.

**Comment by wtrocki** [comment]
This project is dead. I will archive it
