### ISSUE TITLE
Setup codacy for automated code reviews

### ISSUE THREAD

**Issue by harshithdwivedi** [aerogear/offix-android#17]
## Feature Request
 @Lavanyagaur22 can you go ahead and setup codacy for java and kotlin files in the project?
That should help us with automated code reviews for the code we push.

P.S. this shouldn't require you to push any code to the repo; just link the project from the codacy dashboard.

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi Would not it include adding codacy.yml file to the repo? Rest, the linking of project from the codacy dashboard is done. Do we need to include the badge?

**Comment by danielpassos** [comment]
+1 for badge. Let's try to use all badge from https://shields.io/

**Comment by harshithdwivedi** [comment]
Ah yes, you will need to add the badge.
I'm not sure about the yaml, but if the steps require you to do so, feel
free to do so.

**Comment by wtrocki** [comment]
Let me know if you will need any admin rights for attaching service to repo

**Comment by danielpassos** [comment]
@wtrocki I've configured the Codacy for this repo already. I mean gave the Codacy access to add the webhooks

https://app.codacy.com/project/aerogear/voyager-android/dashboard
