### ISSUE TITLE
Storing of mutations in offline store

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/offix-android#25]
## Idea
1. When the user is offline, store mutation in a database(implemented through Room).
2. Update UI (optimistic response) and also notify the user that some error occurred while syncing with the net.
3. Check for the network, and when the user comes online, replicate mutation to the server stored in the offline store one by one. Simultaneously delete them from the local database( offline store ) on successful sync.
4. When the database becomes empty, notify the user that sync is successful.

## Top-level requirements

- Key element of the work will be to build offline queue that will hold and persist offline mutations into sql store. 

- Offline changes should be retriggered again after restart

- Users should be notified that change was added to an offline queue.

- Offline mutations should return Offline specific error to UI/developer.

- Offline data should be always visible even after application restart thanks to optimistic responses

- It should be possible to do multiple edits for the same object when offline
It should be possible to create a new object and edit it after.

- After the offline change is replicated users should get a notification to update UI.

<img width="467" alt="Screenshot 2019-05-31 at 21 34 31" src="https://user-images.githubusercontent.com/981838/58733277-fc012f00-83eb-11e9-9ec0-e5b29685df9c.png">

**Comment by Lavanyagaur22** [comment]
@wtrocki @harshithdwivedi How should the mutation be stored? Should the exact mutation be stored as it is, or its objects (I mean the data of the mutation) should be stored?

**Comment by Lavanyagaur22** [comment]
![864499b1-deb8-437b-8c55-11becdc72517](https://user-images.githubusercontent.com/33238323/59501685-afbcf100-8eb9-11e9-812e-c8cb810fd4c9.jpg)

**Comment by wtrocki** [comment]
> Check for the network, and when the user comes online, replicate mutation to the server stored in the offline store one by one. Simultaneously delete them from the local database( offline store ) on a successful sync.

This part I'm not sure about because Android SDK is missing update function (https://www.apollographql.com/docs/react/essentials/mutations/#updating-the-cache) 

This could be another spike. Android client should update the object itself so we looking into the query object only.

Additional proposed step:
Since synchronization is happening outside UI context (we cannot connect to the elements of the UI as they may not be visible/exist) we need to have some type of listener or observable that will notify about the success failures of the queue.

**Comment by wtrocki** [comment]
@harshithdwivedi Would love to see your view on this. This is simple case for the moment but we can also chat about your idea of background sync.

**Comment by harshithdwivedi** [comment]
Hey, for sure.
For the time being, let's assume that we are handling the cases when the user's network changes when the app is open.

In this scenario; using connectivity manager in Android should provide us with callbacks that tells us whether the network was connected or disconnected.

Based on the connectivty, we can perform a server call and then provide the developer with a method that gives them the success/failure notification alongwith the result.

**Comment by harshithdwivedi** [comment]
For background work, since Broadcast receivers at deprecated, we can probably use WorkManager with a Network constraint in our library.

If we register a mock content provider in our library, we should be able to and hook into the host app's lifecycle methods and inside the onStop method of the host app; we can fire a background work that runs every X minutes (only if there's a network connectivity).

Don't worry if this sounds a bit confusing, I'm happy to help with the implementation

**Comment by Lavanyagaur22** [comment]
> Android client should update the object itself so we looking into the query object only.

What exactly this means?

**Comment by Lavanyagaur22** [comment]
Also, finally what we are storing in db? Exact mutation or its fields/data?

**Comment by wtrocki** [comment]
@Lavanyagaur22 Please check what is required to execute client Mutate. 
What are you passing to the mutate function. We will need to replicate the same when offline.

**Comment by Lavanyagaur22** [comment]
We are passing parameters according to the schema to the mutate function. Okay, so should I store these things when offline

**Comment by wtrocki** [comment]
@harshithdwivedi Fully agree. We could split thats into 3 different areas:

- when in app (online offline broadcasts)
- When in app and request fails
- When in background (for sync)

For simplicity, we can just try the first case in this spike

**Comment by wtrocki** [comment]
Actually we decided to not handle case 2,3 in js sdk as they are actually quite complex

**Comment by harshithdwivedi** [comment]
Sounds good, splitting work makes sense to me.

**Comment by Lavanyagaur22** [comment]
@wtrocki @harshitdwivedi storing mutation data (given by the user to update create or delete ) is much easier and also is beneficial rather than saving actual mutation call. For this, I am maintaining separate tables in DB so when offline->online, each table will be emptied one by one and as there are different calls like mutation update matches to a different class, so as mutation create, the call will be made appropriately referring to the correct table. Any suggestions?

**Comment by wtrocki** [comment]
@Lavanyagaur22 Can you share table structure. Are we saving json file as string for specific ID. What will be your preffered storage strategy?

**Comment by Lavanyagaur22** [comment]
@wtrocki How can we save JSON file of mutations? I have checked all options on mutation object, in android, we are not getting json object as in js (from playground when we were sending ), maybe this is happening internally.

Either we can save mutation object with serial number and when we fetch from database, we have to check its type, by type I mean which class it belongs to, like for our sample we have (UpdateTask, CreateTask, build by apollo depending on our schema) and then run mutation by passing the fetched object from db.

**Comment by wtrocki** [comment]
Take look on JS SDK. We storing mutation metadata and actual arguments. As far I have checked both can be represented as JSON

**Comment by wtrocki** [comment]
This is to map generic data to tables. For example : We cannot have table with title column because this is not generic. It is specific to our app. But we probably need data.column that contains JSON

**Comment by Lavanyagaur22** [comment]
<img width="1440" alt="Screenshot 2019-06-17 at 3 10 46 PM" src="https://user-images.githubusercontent.com/33238323/59595990-7cc26980-9114-11e9-88c0-dc4959f9eb20.png">

<img width="1440" alt="Screenshot 2019-06-17 at 3 11 33 PM" src="https://user-images.githubusercontent.com/33238323/59596012-88ae2b80-9114-11e9-80ad-db7036fd0591.png">


This is the table structure in normalized cache.

But I am still trying to get JSON structure of the mutation..
Please tell me one thing:
We will send mutation in android by passing it as an object (which is done by Apollo), we can't send a direct JSON object to the server (this is actually done by Apollo internally) as we can do from the playground. 
Now, Normalized cache data is the thing which gets filled when response return from server and cache data updates, the response we get back is a JSON object, according to our schema which we map to our model class.
So is there a need to get exact JSON data while storing offline?

We can have 3 columns in our table : 

1. Serial number (keeps a count of how many operations in the offline queue)
2. Query syntax/ schema, which will help us to match to the correct class while making a network call.
3. Query data, which we will fetch from DB, pass it in mutation and make a server call.


<img width="350" alt="Screenshot 2019-06-17 at 3 24 42 PM" src="https://user-images.githubusercontent.com/33238323/59596209-e0e52d80-9114-11e9-846c-0d4f79424237.png">
This goes to the server while making a call, but still trying to get this :p

Also even if we get this, what will we do of it?

We can store query document string alone in a column and data of it in a seperate column
What say @wtrocki @harshitdwivedi?
