### ISSUE TITLE
Android library release?

### ISSUE THREAD

**Issue by mgobins** [aerogear/offix-android#26]
I use https://github.com/aerogear/offix
Is this project try to make offix for Android? 
Where I can see library (repository is only sample app)?
Is IOS library made?

**Comment by mgobins** [comment]
I cann't find any info in https://offix.dev

**Comment by Lavanyagaur22** [comment]
@mgobins Yeah, this is kind of offix for android. Work in progress :p. You will find the library soon :)

**Comment by wtrocki** [comment]
@mgobins Feel free to watch this repository for releases. 
We hoping to have something released in 1-2 months scope. 
As for IOS there are no repository created yet, but if there will be interest from community we can consider making IOS version of library as well.

Offix.dev is now dedicated for JS version only as this is the only production version of the library, but we going to restructure that later.

**Comment by wtrocki** [comment]
This was to release lib. Maybe keep this open to notify people once that is done

**Comment by harshithdwivedi** [comment]
Ah ok, will do.

**Comment by wtrocki** [comment]
I think we can try release soon to extend docs. WDYT? Guys

**Comment by wtrocki** [comment]
offix means offline fix so offixoffline is strange. Maybe we can drop offline?

**Comment by harshithdwivedi** [comment]
Makes sense, @Lavanyagaur22

**Comment by Lavanyagaur22** [comment]
So should I change the offix-offline to offix?

**Comment by wtrocki** [comment]
yes. It will be much better

**Comment by harshithdwivedi** [comment]
@mgobins We have released the initial version of our Android Library.
https://android.offix.dev/#/

Please test it and provide us with your feedback :)
