### ISSUE TITLE
Approaches on Offline Listeners for the Mutation Store.

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/offix-android#30]
## Description 

Our library will have offline listeners for the stored mutations when the client is offline. 
We can simply have 2 callbacks, one for offline error and another for success.

### Approaches to be discussed.

**Comment by wtrocki** [comment]
The listener can have a method that offline operation was successful, but this will raise problem that we will need to know the class of that object to really access their fields. Alternative will be to pass JSON like object but it will mean that we will mean double parsing if someone wants to access the property to build notification.

I think that the sensible way will be to work with casting objects. 
We return object and global implementations can use multiple casts to check what type of object is used. 

Alternatively will be to build listener that will allow to register specific watchers for offline caches for a specific class (however this can be harder to implement and handle). 

Apart from the succcess method might need to have a failure (using Throwable) and maybe additional methods when the item is enqueued or queue was emptied/

**Comment by Lavanyagaur22** [comment]
> I think that the sensible way will be to work with casting objects.
> We return object and global implementations can use multiple casts to check what type of object is used.

For casting objects, we would have to check by casting it to each type of the build classes of mutation.
In case user has more classes let say 20, would it be feasible to check by casting it to each and every class?

Also, as you suggested we can store the class names in a db along with the mutation, what's the problem in that?

**Comment by wtrocki** [comment]
The listener will be on the app side (not library) so dev can cast to many different types etc. Still not perfect so this requires investigation if we can do something better.
