### ISSUE TITLE
Problem facing in adding mutation objects to the offline Queue.

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/offix-android#31]
## Description 

( In reference to solving issue #29  )

I have used an ArrayList (of Type <Any>) which store mutation objects in OnFailure() method of Mutation Callback in UserData() class.

I have made n interface CustomApolloCall which extends ApolloCall and in its Enqueue and Callback method passed Void as a generic type.
Similar thing I have done with CustomMutation interface which extends Mutation.

In MainActivity, I have an offOn Button (for spike) clicking on which should fetch mutation object from the list and make a call to the server.

<img width="668" alt="Screenshot 2019-06-25 at 10 50 14 AM" src="https://user-images.githubusercontent.com/33238323/60071306-477ed280-9737-11e9-8ade-1c6953d78865.png">

### Problem:

When passing mutation object from ArrayList to apollo call, I casted it to be of type CustomMutation, but ClassCast exception came: 

<img width="1374" alt="Screenshot 2019-06-25 at 10 51 34 AM" src="https://user-images.githubusercontent.com/33238323/60071303-4352b500-9737-11e9-8f02-08d457be722b.png">

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi Can you look at it, please :)

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi @wtrocki Can any of you please have a look at it :)

**Comment by harshithdwivedi** [comment]
What's `CustomMutation` here @Lavanyagaur22 ?
I think that the arraylist should be of the type `Mutation` since that's implemented by all the generated classes.
![Snipaste_2019-06-25_11-17-58](https://user-images.githubusercontent.com/47669588/60072438-17d1c980-973b-11e9-87f6-ef4f3118ba03.png)

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi Probably yes, I thought of making a CustomMutation taking Void as generic param while it could have passed to Mutation Only.

It's working 👍
