### ISSUE TITLE
GraphQL Android Proposal

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix-android#4]
# Conflict Resolution and Offline Support for the Aerogear Android SDK

## Project Introduction

AeroGear Mobile Services provides solutions to common development challenges faced by mobile developers. Data Sync is one of the key features provided by the Aerogear Mobile Services to keep the server data and the client data in sync with each other along with the additional capabilities like providing Offline Support to the users, strategies to resolve conflicts, etc.. which needs to be implemented in the Android SDK. This would include
- Using GraphQL to design the APIs for the mobile app.
- Adding real-time data synchronization to the mobile app.
- Adding offline support to the app.
- Resolving conflicts that might occur, with flexible conflict resolution strategies.

## Current Status of the Project

The Voyager framework is built on top of Apollo GraphQL implementation. The Android SDK for AeroGear Mobile Services lacks the support for Voyager framework at the moment. This proposal aims at building an Android SDK and adding the Data Sync ( Data Synchronization using Voyager Framework ) feature to it which will include :
- Utilizing the existing Apollo-Android functionalities with some additional capabilities to provide - - CRUD and cache features in the Android client.
- Offline Support to the users ( making offline edits and detecting them). 
- Conflict resolution for Aerogear android SDK. 

## Project Goals

- #### Utilize the existing Apollo-GraphQL client and adding additional capabilities for the users
With the help of the SDK, users will be able to utilize the existing Apollo-GraphQL to provide create/read/update/delete (CRUD) and Cache implementation (Client will be using the Apollo Cache layer and the cache will be used to hold data that can be fetched when the client is offline) and extend it to add more functionalities listed below.

- #### Provide Cache for Mutation Queries
The Apollo Android Cache currently provides Cache implementation for the GraphQL Queries only. We will be using the existing Apollo Cache along with providing some additional functionalities to implement a cache for mutation queries too.

- #### Provide Offline Support to the user
The SDK will provide support for performing GraphQL operations while offline. Queries and mutations will be held in the queue ( database ) that would be configured to hold requests when the client goes offline. Android Client will offer a set of features to perform data operations when offline. Thanks to offline mutation store users can stage their changes to be replicated back to the server when becoming online.

- #### Implement Conflict Resolution in the Android SDK. 
Since the  SDK allows users to modify data while offline; the users most likely will have to deal with conflicts. Conflict resolution will ensure that the server data and the client data will remain in sync with each other.

## Roadmap

- Creating an Android Library 
- Implementing Offline Support
- Project Documentation 
- Creating a sample application
- Publishing the library
- Community Outreach ( Tech blogs, etc. ) 
- Conflict Resolution 
- Project Documentation 
- Creating a sample application
- Publishing the library
- Community Outreach ( Tech blogs, etc. )

**Comment by harshithdwivedi** [comment]
### Update 
So far we have : 
1. Accomplished Offline Support when the app is opened
2. Accomplished Offline Support when the app is closed
3. Created a sample app with possible use-cases
4. Documented the project
5. Released the Library

**Comment by harshithdwivedi** [comment]
## Update 
**In the new update, the library:** 
1. Supports relationships in offline sync
2. Gets rid of the custom enqueue method thereby providing a streamlined user experience for developers
3. Allows for conflict resolution by allowing the developer to write a custom Conflict Resolution strategy
4. Has a reduced .aar size
5. Has an easy to understand and intuitive sample app

**Features in development are:** 
1. Providing developers an easy way to fetch the base from the cache
2. Offline Sync when the app/device is restarted
