### ISSUE TITLE
Roadmap For Offline Implementation in library.

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/offix-android#44]
![offline2](https://user-images.githubusercontent.com/33238323/61047332-e1fc3880-a3fc-11e9-87de-486e54d92905.jpeg)

**Comment by wtrocki** [comment]
It will be cool to also see the end user API of the Library as well. We have internals but it may be hard to imagine how API/lib will be used.

**Comment by wtrocki** [comment]
What you mean by "Try to store callback"?

**Comment by Lavanyagaur22** [comment]
Actually, this was the approach I thought of. So mentioned that if we try to store callbacks, things can get a little bit easier. So I will be trying the same.

**Comment by wtrocki** [comment]
If they are code not data how we can store callbacks effectively?
They are usually inline so we cannot serialize them etc.

**Comment by Lavanyagaur22** [comment]
We would be storing callbacks only if are the app is in foreground, in-memory approach as List<Callbacks>. We will not be storing them in the database (which works when the app is in the background ). For persistence, we have different approach(reflection).

**Comment by wtrocki** [comment]
I would love to see some experiments on how this could look like but it sounds interesting. Btw.. We are doing the same in js land but we do not hold callbacks ourselves but passing them to users to they can connect to them directly.

**Comment by wtrocki** [comment]
Btw. There is to way to do UI binding for background tasks. The only thing we can do is really to hold some events register but this can be too much really.

**Comment by Lavanyagaur22** [comment]
> The only thing we can do is really to hold some events register but this can be too much really.

Can you please explain a bit more on this? :)

**Comment by Lavanyagaur22** [comment]
UI bindings will not be a problem if the client uses subscriptions in his/her application I guess :p

**Comment by wtrocki** [comment]
hmm.. it depends. Subscriptions are usually UI component bound and not application wide. I think as long things land in the cache we are fine.

**Comment by Lavanyagaur22** [comment]
We need an apollo client in our library for making offline calls. It's possible in 2 ways: 
1. Either we make our own apollo client (with minimal functionality like adding interceptor, okhttpClient, normalized cache, defaultHttpCachePolicy, etc on it which we need to make a call when we are offline) and also provide an extension function to the client with `ApolloClient.Builder()` as the receiver parameter and the client can add additional functionality on the apollo client according to the app-specific requirements. 
2. In the extension function (we have already made) `ApolloCall<Any>.offQueue` (where the receiver parameter is ApolloCall and the function name is offQueue), the user will always have to use `offQueue` of our library instead of `enqueue` provided in Apollo Call. So what we can do is we can take the apollo client as one of the parameters along with other parameters which are mutation object and callback. In this case, we will not make any apollo client but will use a reference of this apollo client provided by the user (which he/she has made in the application following the singleton pattern). (We would have to make a static reference to this client)

Like this: https://gist.github.com/Lavanyagaur22/b0a144a1e86ab08f8c4f7c656bf9ddab

@wtrocki @harshithdwivedi Which approach do you suggest? Also if you have any approaches let's discuss on them :)

**Comment by harshithdwivedi** [comment]
@Lavanyagaur22 I think a mix of these 2 methods will work.
While creating our own minimal ApolloClient will work; it might be a problem if the developers are using their custom auth headers.
However, we can probably store this info inside a database and then recreate the client if the info is serializable.

@wtrocki what do you think?

**Comment by wtrocki** [comment]
Basing on my experience it is easier to let people to create clients with our components (like have them in example) rather than encapsulate client and provide extensions. For example if someone want to add another interceptor to okhttp etc this will be very easy. Same with cache. It doesn't matter what cache you use as long cache-first strategy is used. 


This means:
- More complexity to create client, but we can provide helper class in example that people can literally copy paste and be happy about it. If this will be in the lib they will need to fork it and make the changes
- Less work
- Less hassle of thinking about what to expose and customize

We need example app to be now cleaned and integrated with the library usimg this approach first. Code speaks better than any words :D

**Comment by harshithdwivedi** [comment]
Yep, we can add methods to the default Apollo builder, but we will need to create a client if we want to sync the changes when the app is closed and in the background (because in that case we can't acess the client that the user created).

What do you think is a good approach for that scenario?

**Comment by Lavanyagaur22** [comment]
> it is easier to let people to create clients with our components

Then we have to store a reference to the client and in case the app is closed then we will not be able to make network calls when net comes as we need an apollo client for the same. Please correct me if I am wrong?

> * More complexity to create client, but we can provide helper class in example that people can literally copy paste and be happy about it. If this will be in the lib they will need to fork it and make the changes

Also, can you please elaborate on this further?
@harshithdwivedi So we are making extension function on Apollo Builder?

**Comment by harshithdwivedi** [comment]
@lavanyagaur22 as i outline earlier, let's first focus on the foreground implementation.
Once that's done, we can move to background impl and creating our own client

**Comment by wtrocki** [comment]
We need class that can accept client in constructor meaning that users will create client and pass it over to offline engine

**Comment by wtrocki** [comment]
> @Lavanyagaur22 as i outline earlier, let's first focus on the foreground implementation.
Once that's done, we can move to background impl and creating our own client

Pretty much this! I'm not even sure if background sync is an desirable feature for the library. If we thinking about timers etc. this sync can affect battery life etc. 
Good feature but not a must and certainly not at this point where we need to make it work for the regular cases itself

**Comment by wtrocki** [comment]
Follow up for this issue. Lets create issue for background support. We can ping @danielpassos and @summerspitman for additional feedback - if we should support background at all
