### ISSUE TITLE
Document the codebase

### ISSUE THREAD

**Issue by harshithdwivedi** [aerogear/offix-android#48]
Properly document the current codebase, the docs should include : 
1. Brief overview of the libraty
2. Installation steps
3. Sample usage (with a screenshot/gif if possible)
4. Bugs
5. Features in development

@Lavanyagaur22 this should be your number 1 priority.

**Comment by Lavanyagaur22** [comment]
Since our library is not published, the user will have to clone this project and make a sample app in it putting the library dependency in Gradle. So do I need to mention this?

**Comment by wtrocki** [comment]
Assume library is published

**Comment by harshithdwivedi** [comment]
Yeah, just assume that library is published and add a placeholder
dependency for now.
