### ISSUE TITLE
Discussion on the Conflict Resolution Strategies for the library.

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/offix-android#53]

**Comment by wtrocki** [comment]
@Lavanyagaur22 I will recomend to check the current implementation of conflict inside offix library and follow up with questions: https://github.com/aerogear/offix/tree/master/packages/offix-offline/src/conflicts

See also documentation in offix.dev
We need to translate requirements into Android land or even do things differently based on experience. Let's have a discussion here.

**Comment by wtrocki** [comment]
I think might need to bring sample ionic server app inside repository for convinience and trying things up with conflicts

**Comment by Lavanyagaur22** [comment]
Also, for conflict resolution, we would have to maintain 3 objects of a class ( this class is a POJO of the request body sent from the client to the server, POJO can be made by analyzing json object ), one is the `client data` (which client is trying to modify, we can get this from interceptor), the other is the `base` (which we would have to extract from cache, this being the apollo cache as our library using apollo ) and other is the `server data` ( to get the server data we would probably have to store the data response, this we can get from the interceptor on each call to the server, i.e we would have to store server data related to each object and on every call to the server).

**Comment by Lavanyagaur22** [comment]
Now comes the point that how we are going to fetch details of base? ( as we have to extract it from apollo cache).

@harshithdwivedi @wtrocki WDYT?

**Comment by wtrocki** [comment]
Yes.. For that we need to know the id and also have access to cache raw data. 
It was tricky on js so this will be the first investigation. 

However I would recomend to not think about the base now. Let's have vision how conflict resolution is implemented but I wll start with something that caches conflict error from server, let dev to handle it in resolver function and then send it back. This is prototype that we can extend later.

**Comment by Lavanyagaur22** [comment]
@wtrocki Can I try we the version based approach first? Because our schema is based on this.

**Comment by wtrocki** [comment]
Yes.. No plugability is a good start.

**Comment by Lavanyagaur22** [comment]
@wtrocki @harshithdwivedi Hey, for now, we are resolving conflicts based on version right?

So after we log whenever we get conflicts (user will be explicitly passing version while performing mutations) we can internally pass the correct version and make another mutation with the same data. Does that makes sense?

**Comment by Lavanyagaur22** [comment]
@wtrocki @harshithdwivedi To resolve conflicts we need both server data and client data. And for this, we need to parse the response we get in error and take out the things from it. Now we are getting the below error response for the schema we are using:

```
json 
{  
   "errors":[  
      {  
         "message":"VoyagerConflict",
         "locations":[  
            {  
               "line":1,
               "column":73
            }
         ],
         "path":[  
            "updateTask"
         ],
         "extensions":{  
            "code":"INTERNAL_SERVER_ERROR",
            "exception":{  
               "message":"VoyagerConflict",
               "conflictInfo":{  
                  "resolvedOnServer":false,
                  "serverState":{  
                     "title":"Task1",
                     "description":"h1",
                     "version":2,
                     "id":1,
                     "status":"OPEN"
                  },
                  "clientState":{  
                     "id":"1",
                     "title":"Task1",
                     "version":1
                  }
               },
               "stacktrace":[ + ]
            }
         }
      }
   ],
   "data":{  
      "updateTask":null
   }
}
```

We can parse this response in our library and can use to resolve conflicts if we get response data as null (which means conflict has happened). After resolving them we can again make a call to the server from the library. WDYT?

**Comment by wtrocki** [comment]
Yes. This in very simple terms explain the workflow on the js-sdk

**Comment by wtrocki** [comment]
This disussion got little bit dated. Closing as we can create couple follow up
