### ISSUE TITLE
Extending apollo client by adding offline object

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix-android#57]
I think we might refactor code of OfflineList. Name suggest that this is a list but it is used for various reasons. We use it as singleton and also using statics. How about we have offline object as extension of ApolloClient class?

This way will be much cleaner and we will always have access to client

https://github.com/aerogear/offix-android/blob/693566cd6564cf4c6d2121715e02ff78573dda4a/offix-offline/src/main/java/org/aerogear/offixoffline/Offix.kt#L35

**Comment by harshithdwivedi** [comment]
+1 for renaming; -1 for an extension variable, Kotlin doesn't allow for it.
A good read : https://stackoverflow.com/a/36502482/5471095

**Comment by wtrocki** [comment]
Something like `getOffline()`. I think if we use instance all the time it will be nice.

**Comment by harshithdwivedi** [comment]
Closing this as we're using an instance of the client.
