### ISSUE TITLE
Question - Callback store

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix-android#58]
Any reason we store callbacks instead of using our own one.
After restart we can use generic one for sure.
Do we have any global listener for offline queue? Like queue emptied?

https://github.com/aerogear/offix-android/blob/693566cd6564cf4c6d2121715e02ff78573dda4a/offix-offline/src/main/java/org/aerogear/offixoffline/OfflineSyncService.kt#L27

**Comment by Lavanyagaur22** [comment]
Users can have UI bindings in the onResponse() of their callbacks. So storing them can help us in UI bindings. 

We can also use the generic one for sure where callback is of type ApolloCall.Callback<Void> but then UI bindings are a problem.

**Comment by wtrocki** [comment]
I think that this is a recipe to fix stuff after restart. We can have references to real ones and  if they are gone then we simply use generic one that users can provide. Generic one sadly will require typecasing if you would like get access to object.
