### ISSUE TITLE
Query persistence as part of the library?

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix-android#59]
WDYT about having some documentation about cache setup. Do you think we can have it as part of the lubrary

**Comment by Lavanyagaur22** [comment]
We are using apollo cache for now. So are you referring to the documentation for the same?

**Comment by wtrocki** [comment]
Yeah.. Without cache-first strategy offline approach will not work. 
Not sure if we should provide some stuff in library. 
Probably not easy so we can document it.
