### ISSUE TITLE
Example type converters may be not needed

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix-android#60]
Some code were moved to library

**Comment by harshithdwivedi** [comment]
You mean TypeConverters?
I think we might need them for saving the muatation to db.

**Comment by wtrocki** [comment]
I meant this: https://github.com/aerogear/offix-android/tree/master/sample/src/main/java/org/aerogear/graphqlandroid/persistence

This is part of the library?

**Comment by Lavanyagaur22** [comment]
> I meant this: https://github.com/aerogear/offix-android/tree/master/sample/src/main/java/org/aerogear/graphqlandroid/persistence
> 
> This is part of the library?

No, this is not a part of the library for now. Will be required in background sync #61
