### ISSUE TITLE
Adding support for background sync for mutations

### ISSUE THREAD

**Issue by harshithdwivedi** [aerogear/offix-android#61]
As of now, the mutations are lost when the app is closed.
The idea is to store them into a database and schedule a worker that automatically syncs them with the server when the device has network connectivity.

**Comment by Lavanyagaur22** [comment]
What should be the approach taken for apollo client then? 
For now, we are not having a client in the app and are taking it from the user itself. For the background sync, we probably need an apollo client.

**Comment by harshithdwivedi** [comment]
Have a look and see if you can serialize your Apollo client?
If you can, then it will be very easy to store it to the db and then recreate it later on.

If not, then we might want to create a minimal version of the client using the info that the user provided while creating it.

**Comment by wtrocki** [comment]
This is an good question to have directly on the apollo repository. What we looking for here is to have the ability to run client in background without recreating it.

From top of the head we can ask user to provide function that he is using to create client - buildClient when initializing background feature. Is that doable?

**Comment by Lavanyagaur22** [comment]
> This is an good question to have directly on the apollo repository. What we looking for here is to have the ability to run client in background without recreating it.
> 
> From top of the head we can ask user to provide function that he is using to create client - buildClient when initializing background feature. Is that doable?

Okay, I will open an issue in apollo repo for the same.

Also, even if we ask for a function from the user it will be lost ( if not saved) when the app is closed. And for saving we neeed to serialise it in any case and serialising a function is more difficult than to find a way to serialise client.

**Comment by Lavanyagaur22** [comment]
@danielpassos @secondsun  WDYT on adding background sync for offline support. We have the offline support implemented when the app is in the foreground. When the app is closed, offline support is a limitation as of now and to implement it we most probably require an apollo client which we would have to create in our library for the same. For now, we are taking the client from the user. 

Suggestions are most welcome :)

(Also you can have a look at #44 related to Offline Support implementation in the library)

**Comment by wtrocki** [comment]
Pinging @secondsun again (edits are not pinging people)

**Comment by Lavanyagaur22** [comment]
https://github.com/apollographql/apollo-android/issues/1441

We can't serialize the apollo client. Have to make an instance again when in background.

**Comment by wtrocki** [comment]
Frim my point of view this do not change much. People create client themselves and trigger offline engine based on client

**Comment by danielpassos** [comment]
@Lavanyagaur22 Sorry I don't have too much context here but...

Run something in background is not a big problem we can use something like [services](https://developer.android.com/guide/components/services)

The only problem is how to re-create the stack on the service when the device got restart or the app got killed. Do you have it storied somewhere?
