### ISSUE TITLE
How we going to create issues

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix-android#7]
## Proposal

We can have a general proposal for 3 months work. 
We can split work to individual technical tasks as follows:
![Screenshot 2019-05-31 at 15 24 04](https://user-images.githubusercontent.com/981838/58712343-4ff22080-83b8-11e9-8d04-41052f2d96b9.png)

ping @harshithdwivedi @wtrocki for idea

**Comment by wtrocki** [comment]
Yeah that works for me

**Comment by harshithdwivedi** [comment]
Looks good 👍
