### ISSUE TITLE
Explore the generated files

### ISSUE THREAD

**Issue by harshithdwivedi** [aerogear/offix-android#77]
@Lavanyagaur22 maybe it's also a good idea to manually edit the schema in our code to contain nesting and see what the constrictors for the generated files look like.

Post your research in the comments of this issue so that we can see how to go about adding support for them.

**Comment by Lavanyagaur22** [comment]
Sure, going to put the research for the nested structure here.

**Comment by wtrocki** [comment]
Graphback will generate all now so I would.recomend to use it simply because we can generate complex use cases with zero time investment
