### ISSUE TITLE
Create the starter Android SDK

### ISSUE THREAD

**Issue by harshithdwivedi** [aerogear/offix-android#8]
Create and add the started code for the library.
Tasks : 
1. Create a sample app under the library that uses the methods available in the apollo-graphql dependency

**Comment by harshithdwivedi** [comment]
Add Pull Request and Issue template to the repository

**Comment by wtrocki** [comment]
From me:
I will be nice to have minimal docs in readme how to run the example project.

**Comment by harshithdwivedi** [comment]
@Lavanyagaur22 I've been doing some research on my end and it might be a good idea to skip the android library for now.

What I would recommend is that you go ahead and play around with the app that you've [created earlier](https://github.com/Lavanyagaur22/GraphQL-Android-Example) and research around the implementation and the API design of the features available in the graphql SDK.

**Comment by wtrocki** [comment]
@harshithdwivedi Nice idea. Generally the longer we withhold creating library(ies) then better. What I have been doing is like performing experiments on the running application, writing blog post and doing community demo to collect feedback and after that creating a library. It is simply way faster to build some prototype on the app itself and harder to make it a generic inside the library - we we will get there for sure.

To really get to know what is the problem we can simulate that into app.

**Comment by wtrocki** [comment]
How about we create following repo structure:

```
/.github
/docs
/example/ example app
/libs
README.md
```

The starting point here will be to have an application that: 

- have a simple view where we can edit perform both queries and mutations.
- uses Apollo cache as implemented in sample
- Configures external okhttp library

Literally all that was already spiked in another repository 
(however, we might start fresh if you think it's useful)

**Comment by Lavanyagaur22** [comment]
@wtrocki @harshithdwivedi I think we can start with a fresh android application (based on that sample one) and adding more features to it. Also, I'll add some unit tests for the same in it.

**Comment by danielpassos** [comment]
@wtrocki In your folder proposal what the `libs` folder is?

**Comment by wtrocki** [comment]
My bad. I wanted to denote that each lib will be on root. So it will be something like offline, conflict and so on
