### ISSUE TITLE
Setup build process for repository

### ISSUE THREAD

**Issue by wtrocki** [aerogear/offix-android#9]
## Proposal

Setup build process in CI for the repository to check every PR.

Setup an example app builds in CircleCI that will be running for each pr. 
We can use this for inspiration.: https://github.com/aerogear/aerogear-android-sdk/tree/master/.circleci

Additional info: https://circleci.com/docs/2.0/language-android/

Note: this is may require some unit tests in example applications first so not high priority for the moment.

**Comment by danielpassos** [comment]
@wtrocki It still valid without any unit test. The CI will at least test if it still building. It's really nice specially when you start to introduce a third-party libs

**Comment by wtrocki** [comment]
Agreed. We can just start building sample app
