### ISSUE TITLE
Query on Conflict error message.

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/offix-android#93]
Actually, have a doubt regarding the error json response. Are the keys `serverdata` and `clientdata` going to remain the same in every conflict message irrespective of the server used?

<img width="421" alt="Screenshot 2019-07-31 at 6 26 34 PM" src="https://user-images.githubusercontent.com/33238323/62213527-c0b9b700-b3c0-11e9-9bca-849a19a0a0fd.png">

**Comment by wtrocki** [comment]
Yes. Please check https://offix.dev/#/ref-conflict-server for more info

**Comment by Lavanyagaur22** [comment]
Yes, so this library is going to work with this type of structure for conflicts only. So we can parse it according to the defined structure.

**Comment by wtrocki** [comment]
yes.. This is the contract we have made and document for users and it will not change.
