### ISSUE TITLE
Query regarding the "version" key in schema.  

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/offix-android#96]
Will the `version` key always be present in `serverstate` in the schema? It was actually not there on the Offix Website inside the conflict structure but in js sdk, version is used to resolve conflicts. Because if we have the version in the sample place always, it will be easy for us to parse the json for the version

"conflictInfo":{  
                  "resolvedOnServer":false,
                  "serverState":{  
                     "title":"Task1",
                     "description":"h1",
                     `"version":2`,
                     "id":1,
                     "status":"OPEN"
                  }

**Comment by Lavanyagaur22** [comment]
@wtrocki https://github.com/aerogear/aerogear-js-sdk/blob/2.5.0/packages/sync/src/conflicts/VersionedState.ts#L19

**Comment by wtrocki** [comment]
I think this is because this is showcase default implementation. 
Take look into offix documentation. I will recommend to write some different state marker like - last updated field instead of version

**Comment by Lavanyagaur22** [comment]
@wtrocki 
Is it not the `version` field on the basis of which Conflicts are resolved in js SDK?
I am referring to the default conflict Implementation https://offix.dev/#/ref-conflict-client?id=default-conflict-implementation

**Comment by wtrocki** [comment]
See it is called default conflict implementation that can be **changed** we do not hardcode `version` anywhere etc. and we should not do it on Android as well.

**Comment by Lavanyagaur22** [comment]
@wtrocki Do you recommend having a custom implementation provided by the user of the library as to which key we should consider during resolving conflicts?

For example, they can provide a simple string named CONFLICT_KEY in their strings.xml as to which key we should use?

If not provided, we can use the version key.
WDYT?

**Comment by wtrocki** [comment]
Key to make useful library is to understand the problem we want to solve and premise of this problem. Data can come with all different shapes and it can cause conflicts but devs need to define what conflict mean. This is not only field related. For example we can decide to calculate some hash from object and compare it. Conflict can be caused in many ways. On client we do not need to care at all as conflict comes from server and version is used only to detect the conflict. Please check server implementation in offix for more info.

**Comment by wtrocki** [comment]
> If not provided, we can use the version key.

What will be purpose of the version key? Why we need to use it? I'm not sure if I understand the top level question here.

Lets check how server side conflict works and implement it on top of graphback. Push it to some branch and ping me. This will allow us to get better understanding. Without that it will be hard to communicate about the problem we are facing and approach we took in server. Server might have some tradeoffs and drawbacks but idea is very simple. Lack of clarity makes me feel that we need much better docs for offix and this

**Comment by harshithdwivedi** [comment]
@wtrocki adding to @lavanyagaur22's question here.
If the nature of conflict resolution will be specified by the user, how does that fit in the library that we are trying to make?

We need to understand how to manipulate the response that we receive in order to resolve the conflict and this will again be specified by the user.

Based on your explanation it seems like the best way to go about this would be to simply return the serverState and clientState back to the Developer in a callback so that they can use their own implementation to resolve it and make a call back to their server.

How do you envision that we do this with a statically typed language and a library ; because we want to make our library flexible and robust.

We don't want the user to do too much work that results in the library being useless and we don't want them to do too little either that causes the library to be rigid.

**Comment by Lavanyagaur22** [comment]
@harshithdwivedi Yeah, I totally agree with it. 
@wtrocki We can have a method in the `ResponseCallback` named `onConflictCallback`.

```kotlin
client.enqueue(mutation, object : ResponseCallback){ 
onSucess(response){..}
onSchedule(mutation){...}
onConflict(serverstate, clientstate){...} })
```

From inside the callback, we will return the `serverstate` data and `clientstate` data to the user. The user knows the structure of their schema, graphQL files and they can parse the server data and client data json responses accordingly. After resolving conflicts on the client, they can again make a call to the server with the mutation.

WDYT?

**Comment by Lavanyagaur22** [comment]
> Data can come with all different shapes and it can cause conflicts but devs need to define what conflict mean.

Also then as we are making a library, how will we come to know that on what basis the client wants to resolve data, on basis of version, hash from the object or things like that. Either we need to take the factor for resolving conflicts from the client but then it would totally depend on their schema and their choices a well.

Server-side implementation in Offix is also based on `Version Based Conflict Resolution`. Rest of the approaches like Calculate hashes of the data, Use a specialized field like last change date, have separate storage with history of the changes etc can be implemented but then we need to know while making the library that on what basis we are resolving conflicts.

**Comment by harshithdwivedi** [comment]
Hm, yeah this makes sense to me.
We can start with this in our library and build upon this, why don't you go ahead and send a PR alongside working with schema extension with GraphBack

**Comment by wtrocki** [comment]
> Server-side implementation in Offix is also based on Version Based Conflict Resolution

I think you meant to ionic-showcase sever application. Offix server offers a range of implementations for detection + gives devs ability to build their own (https://github.com/aerogear/offix/tree/master/packages/offix-conflicts-server/src/states). We should not care about this at all as this is server-side responsibility.

My suggestion will be to have something like:
```java
 JSONObject onConflict(JSONObject serverstate, JSONObject clientstate){
	// This makes no sense as it will override the changes but 
    // but users will be able to provide their own way of resolution in UI etc.
    clientState.setString("version", serverState.getString("version"))
    return clientState;
 }
```

Where we envision using version or anything else for conflict resolution?
Conflict resolution is done outside library - library just need to process error from server and trigger separate callback that user will provide where they deal with conflict (asynchronously with ability to do UI binding)

**Comment by wtrocki** [comment]
Schema for graphback will look like this: 

https://github.com/aerogear/ionic-showcase/blob/master/server/src/tasks/schema.js#L6-L18

But we might need to extend it for our own needs to drop some relations etc.

**Comment by Lavanyagaur22** [comment]
> Conflict resolution is done outside library - library just need to process error from server and trigger separate callback that user will provide where they deal with conflict (asynchronously with ability to do UI binding)

Okay, so our library would detect conflicts and upon detection of conflicts we are going to return server data and the client data to the user and they can deal with it accordingly. 

@wtrocki Please correct me if I'm wrong?

**Comment by harshithdwivedi** [comment]
Yeah, I think that's correct.
@lavanyagaur22 feel free to go ahead with @wtrocki's suggestion and send a
PR.

**Comment by wtrocki** [comment]
Server detects conflict. Library detects error from server. Calls callback. Waits for resolution. Sents data again.

Updated example above

**Comment by Lavanyagaur22** [comment]
> Waits for resolution.

This is done by us (devs) or by the user then?

**Comment by Lavanyagaur22** [comment]
> Waits for resolution.

This is done by the users then. So the flow can be like:

1. In callback, we detect error from the server.
2. Give the client data and server data to the user.
3. They resolve the conflicts.
4. Somehow we have to know on our side that conflict is resolved.
5. And then again make a call to server-> this is our job to make a call to the server with the 
    correct data. (and resolving conflicts is the job of the user)

**Comment by harshithdwivedi** [comment]
@lavanyagaur22 we can make the onConflict method return a Mutation Object, so when the developers resolve their conflict, they send a Mutation object back to our library.

Using that object, we can resync stuff with the server.

That would be ideal I think.

**Comment by harshithdwivedi** [comment]
Also, instead of passing the serverState and clientState as JSON object, let's pass it as normal strings?

Developers often use GSON to parse their json and GSON doesn't support JSONObject so they'll have to convert it back to a string again.

@wtrocki what do you say?

**Comment by wtrocki** [comment]
I think HashMap will be more hands on, but strings will be more flexible. Keep on mind thst server might have data that is not mapped in client. No preference

**Comment by harshithdwivedi** [comment]
Let's start with String for now then and change things based on the
feedback.

Using hashmap might give us issues with relationships.

**Comment by wtrocki** [comment]
Ah.. best way is to not support relationships for conflicts at all. Mutations with relationships are rare.

**Comment by Lavanyagaur22** [comment]
> Ah.. best way is to not support relationships for conflicts at all. Mutations with relationships are rare.

@wtrocki Can you please explain what do you mean by **mutations with relationships are rare**? If it is so, then why we want to solve them for nested schema?

**Comment by Lavanyagaur22** [comment]
Also, we can use hashmaps but they might cause problems with the relationships.

**Comment by wtrocki** [comment]
Hmm.  How we see conflicts working for relationships? This will be quite hard as we have access to state on root field only (e.g. version)

**Comment by wtrocki** [comment]
Any example for mutation that have relationship? Relationships are usually for queries.

**Comment by wtrocki** [comment]
We can certainly introduce relationship support on server but I will love to see example mutation that we could see working. GraphQL have operation based replication system - this means that parameters we send to server can affect multiple business objects. Each business object update can mean conflict on it is own. With offix conflict we always assume 2 things:
- update is affecting single business object
- update is going to hit only root resolver on server

Love to get your ideas/issue in offix repository about how we can change/improve this.

Can you tell what kind of problems with relationships do you see?

**Comment by harshithdwivedi** [comment]
@wtrocki That's interesting.
So you mean to say that we will never have any nested relationships sent when we perform any mutation?

If that's the case then we can probably stop worrying about implementing relationships in offline mode as well; since we don't provide offline support for queries, only for mutations.

Interesting stuff, let me know what you think

**Comment by wtrocki** [comment]
InputType passed to mutation generates nested structure. For offline we need persist mutation parameters that will be nested. Conflict is always object based and not operation based. Which means that in callback you getting entire object state from server and actual client state. No nested data should appear in this case.

This is very simple when visializing

Mutation is github commit. Single commit can generate multiple conflicts and resolution focuses on object rather on what was passed by commit.

We support only single object now which is shame. Would you do me a favour and put this idea into offix as issue. I would live to talk about this with our community

**Comment by harshithdwivedi** [comment]
Sure thing, I'd let @Lavanyagaur22 do the honor of opening the issue in offix repo for relationship support with mutations.

However, I'm still a bit unclear on this entire workflow.
I always assumed that we can expect mutations with relationship; for example, if I want to add a new book by an author into a library's database and the author is a relation in the book object.

@wtrocki is something like this not very common in GraphQl world or is my approach here not an ideal one?

**Comment by wtrocki** [comment]
I think using graphback generated schema can give us some hints here. We use input types for updates

**Comment by harshithdwivedi** [comment]
You mean using this one in our app, for example : https://github.com/aerogear/graphback/blob/master/packages/graphback/example/Note.graphql

**Comment by wtrocki** [comment]
> If that's the case then we can probably stop worrying about implementing relationships in offline mode as well; since we don't provide offline support for queries, only for mutations.

I think we got confused about this. Let's chat about this exclusively to make sure we have a proper understanding.

**Comment by harshithdwivedi** [comment]
Closing this now.
