### ISSUE TITLE
Query regarding the conflict error structure.

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/offix-android#97]
<img width="421" alt="Screenshot 2019-07-31 at 6 26 34 PM" src="https://user-images.githubusercontent.com/33238323/62426232-95580480-b6ff-11e9-89f8-d1af20c93e87.png">

#### This is the error structure I am currently getting with the schema we are using.

```java
 "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "conflictInfo": {
            "serverState": {
                 //..
            },
            "clientState": {
              //..
            }
          },
        }
 }
```
The above one is the one we would be supporting in the library.

What is the reason that we get an **array of errors** in the above one? In what case we can get multiple errors?

**Comment by wtrocki** [comment]
This is comming from graphql specification
